-- Migration: Secure Authentication Flow
-- Fixes:
-- 1. IDOR vulnerability - adds device_code binding
-- 2. Plain text tokens - stores hashes instead
-- 3. Remove long-term Google token storage (use for identity verification only)

-- Table for pending auth requests (device flow)
-- This binds the MCP client to the browser session
CREATE TABLE IF NOT EXISTS auth_requests (
    id SERIAL PRIMARY KEY,
    device_code VARCHAR(64) NOT NULL UNIQUE,  -- Random UUID from MCP client
    user_email VARCHAR(255),                   -- Set after user initiates, before auth
    status VARCHAR(20) DEFAULT 'pending',      -- pending, authenticated, used, expired
    session_token_hash VARCHAR(64),            -- SHA-256 hash of session token (set when authenticated)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    expires_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() + INTERVAL '10 minutes',
    authenticated_at TIMESTAMP WITH TIME ZONE,
    used_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_auth_requests_device_code ON auth_requests(device_code);
CREATE INDEX IF NOT EXISTS idx_auth_requests_status ON auth_requests(status);
CREATE INDEX IF NOT EXISTS idx_auth_requests_expires ON auth_requests(expires_at);

-- Modify session_tokens to store hash instead of plain token
-- We keep the old column temporarily for migration, then drop it
ALTER TABLE session_tokens
    ADD COLUMN IF NOT EXISTS token_hash VARCHAR(64);

-- Create index on hash for lookups
CREATE INDEX IF NOT EXISTS idx_session_tokens_hash ON session_tokens(token_hash);

-- Note: After deploying, run this to migrate existing tokens (if any):
-- UPDATE session_tokens SET token_hash = encode(sha256(session_token::bytea), 'hex') WHERE token_hash IS NULL;
-- Then drop the plain text column:
-- ALTER TABLE session_tokens DROP COLUMN session_token;

-- We can drop oauth_tokens since we only use Google for identity verification
-- But keeping it for now in case there's a use case - just don't store long-term
-- Instead, we'll modify the code to not persist tokens

COMMENT ON TABLE auth_requests IS 'Pending auth requests with device_code binding. Prevents IDOR attacks.';
COMMENT ON COLUMN auth_requests.device_code IS 'Random UUID generated by MCP client - binds client to auth session';
COMMENT ON COLUMN auth_requests.session_token_hash IS 'SHA-256 hash of session token - plain token only sent once';
COMMENT ON COLUMN session_tokens.token_hash IS 'SHA-256 hash for validation - plain token never stored';
