-- Migration 092c: chunk_context column for Anthropic-style contextual retrieval
--
-- Stores a 1-2 sentence preamble per chunk that situates the chunk within
-- its session/topic context. Generated by Pass-2 enrichment script
-- (scripts/pass2_chunk_enrich.py) using gemma-4-31b. The chunk_context is
-- prepended to chunk_text at re-embed time so the embedding captures
-- session-level aboutness in addition to local content.
--
-- Plan: ~/.claude/plans/session-recall-tier-1-expanded.md §P_sample_A2 step 1
-- F2 patch authored 2026-04-28.

ALTER TABLE session_chunks
  ADD COLUMN IF NOT EXISTS chunk_context TEXT;

COMMENT ON COLUMN session_chunks.chunk_context IS
  'Pass-2 contextual-retrieval preamble (1-2 sentences) prepended to chunk_text at embed time. NULL = bare-embedded (default). Populated by scripts/pass2_chunk_enrich.py.';
