#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# ADR-001 Next Steps Orchestrator
# ============================================================
# Usage:
#   ./scripts/adr001/run-next-steps.sh 1|2|3|4|5|all
#
# Each step produces artifacts at expected paths.
# Exits non-zero if any gate fails.
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
FEDERATION_DIR="$PROJECT_DIR/scripts/federation"

# Auto-generate timestamp + short SHA suffix
UTC_TIMESTAMP=$(date -u +%Y%m%dT%H%M%SZ)
SHORT_SHA=$(cd "$PROJECT_DIR" && git rev-parse --short HEAD 2>/dev/null || echo "unknown")
SUFFIX="${UTC_TIMESTAMP}-${SHORT_SHA}"

# Load env if available
if [[ -f "$PROJECT_DIR/config/personal.env" ]]; then
    set -a
    source "$PROJECT_DIR/config/personal.env"
    set +a
fi

export POSTGRES_URL="${POSTGRES_URL:-postgresql://darrenzal:@localhost:5432/personal_koi}"
export DRILL_SEED="${DRILL_SEED:-42}"

# Use project venv python if available
PYTHON="${PROJECT_DIR}/venv/bin/python3"
if [[ ! -x "$PYTHON" ]]; then
    PYTHON="python3"
fi

STEP="${1:-}"
FAILURES=0

usage() {
    echo "Usage: $0 <step>"
    echo ""
    echo "Steps:"
    echo "  1    Soak go/no-go (capture soak-check output)"
    echo "  2    Federation conflict drill (Layer A + B)"
    echo "  3    Graphiti go/no-go decision (append to ADR)"
    echo "  4    Graphiti prototype (only if approved at step 3)"
    echo "  5    ADR decision review (aggregate artifacts)"
    echo "  all  Run steps 1-3 (steps 4-5 are manual/conditional)"
    echo ""
    exit 1
}

step_header() {
    echo ""
    echo "============================================================"
    echo "  Step $1: $2"
    echo "  Suffix: ${SUFFIX}"
    echo "============================================================"
    echo ""
}

# ============================================================
# Step 1: Soak Go/No-Go
# ============================================================
run_step_1() {
    step_header 1 "Vault Sync Soak Go/No-Go"

    local ARTIFACT_DIR="$PROJECT_DIR/docs/soak-results"
    local ARTIFACT="$ARTIFACT_DIR/sync-1.5-soak-${SUFFIX}.md"
    mkdir -p "$ARTIFACT_DIR"

    echo "Capturing soak-check output..."
    echo ""

    # Capture soak-check output
    local SOAK_OUTPUT
    SOAK_OUTPUT=$(bash "$FEDERATION_DIR/soak-check.sh" 2>&1) || true

    # Extract key metrics from soak log
    local SOAK_LOG="${SOAK_LOG:-/tmp/vault-sync-soak.jsonl}"

    # Write artifact
    cat > "$ARTIFACT" <<SOAK_EOF
# Sync-1.5 Soak Go/No-Go — ${UTC_TIMESTAMP}

## Soak Check Output

\`\`\`
${SOAK_OUTPUT}
\`\`\`

## Pass/Fail Gates

| Gate | Threshold | Result |
|------|-----------|--------|
| Rejected events growth | 0 new in final 24h | _MANUAL CHECK_ |
| Pending queue ceiling | <= 5 for 3 consecutive | _MANUAL CHECK_ |
| Drift | 0 on 3+ consecutive | _MANUAL CHECK_ |
| Error rate | 0 unrecoverable | _MANUAL CHECK_ |

## Soak Log Tail (last 10 entries)

\`\`\`
$(tail -10 "$SOAK_LOG" 2>/dev/null || echo "No soak log found at $SOAK_LOG")
\`\`\`

## Decision

**Go/No-Go:** _PENDING — review gates above and fill in_

**Rationale:** _To be completed at deadline (2026-03-01 04:31 UTC)_

---
Generated by: \`scripts/adr001/run-next-steps.sh 1\`
Artifact: \`${ARTIFACT}\`
SOAK_EOF

    echo "  Artifact written: $ARTIFACT"
    echo ""
    echo "  NOTE: Review the gates above and update Go/No-Go decision"
    echo "  before the deadline (2026-03-01 04:31 UTC / Feb 28 20:31 PST)"
}

# ============================================================
# Step 2: Federation Conflict Drill
# ============================================================
run_step_2() {
    step_header 2 "Federation Conflict Drill"

    local REPORT="$FEDERATION_DIR/conflict-drill-report-${SUFFIX}.json"

    echo "--- Layer A: Direct SQL ---"
    echo ""
    local LAYER_A_OUTPUT
    LAYER_A_OUTPUT=$(cd "$PROJECT_DIR" && "$PYTHON" scripts/federation/conflict-drill-sql.py 2>&1)
    local LAYER_A_EXIT=$?
    echo "$LAYER_A_OUTPUT"

    # Extract JSON from Layer A output
    local LAYER_A_JSON
    LAYER_A_JSON=$(echo "$LAYER_A_OUTPUT" | grep '^DRILL_JSON:' | sed 's/^DRILL_JSON://')

    echo ""
    echo "--- Layer B: KOI-net Event Replay ---"
    echo ""
    local LAYER_B_OUTPUT
    LAYER_B_OUTPUT=$(cd "$PROJECT_DIR" && "$PYTHON" scripts/federation/conflict-drill-federation.py 2>&1)
    local LAYER_B_EXIT=$?
    echo "$LAYER_B_OUTPUT"

    # Extract JSON from Layer B output
    local LAYER_B_JSON
    LAYER_B_JSON=$(echo "$LAYER_B_OUTPUT" | grep '^DRILL_JSON:' | sed 's/^DRILL_JSON://')

    # Determine overall
    local OVERALL="PASS"
    if [[ $LAYER_A_EXIT -ne 0 ]] || [[ $LAYER_B_EXIT -ne 0 ]]; then
        OVERALL="FAIL"
        FAILURES=$((FAILURES + 1))
    fi

    # Build report JSON
    python3 -c "
import json, sys

layer_a = json.loads('''${LAYER_A_JSON}''') if '''${LAYER_A_JSON}''' else {'results': {}, 'overall': 'FAIL'}
layer_b = json.loads('''${LAYER_B_JSON}''') if '''${LAYER_B_JSON}''' else {'results': {}, 'overall': 'FAIL'}

report = {
    'timestamp': '${UTC_TIMESTAMP}',
    'short_sha': '${SHORT_SHA}',
    'seed': ${DRILL_SEED},
    'layer_a': layer_a.get('results', {}),
    'layer_b': layer_b.get('results', {}),
    'overall': '${OVERALL}'
}

with open('${REPORT}', 'w') as f:
    json.dump(report, f, indent=2)
print(json.dumps(report, indent=2))
" 2>&1

    echo ""
    echo "  Report written: $REPORT"
    echo "  Overall: $OVERALL"
}

# ============================================================
# Step 3: Graphiti Go/No-Go Decision
# ============================================================
run_step_3() {
    step_header 3 "Graphiti Go/No-Go Decision"

    local ADR="$PROJECT_DIR/docs/ADR-001-graph-db-strategy.md"

    if grep -q "Decision:.*COMMIT\|Decision:.*DEFER" "$ADR" 2>/dev/null; then
        echo "  Decision already recorded in: $ADR"
    elif [[ $(date -u +%Y%m%d) -ge 20260304 ]]; then
        # Auto-DEFER: deadline passed with no decision
        if grep -q "Appendix A: Graphiti Decision" "$ADR" 2>/dev/null; then
            if sed --version 2>/dev/null | grep -q GNU; then
                sed -i 's/\*\*Decision:\*\* _PENDING.*/\*\*Decision:\*\* DEFER (auto — deadline passed without explicit decision)/' "$ADR"
            else
                sed -i '' 's/\*\*Decision:\*\* _PENDING.*/\*\*Decision:\*\* DEFER (auto — deadline passed without explicit decision)/' "$ADR"
            fi
        else
            cat >> "$ADR" <<'GRAPHITI_EOF'

## Appendix A: Graphiti Decision (2026-03-04)

**Decision:** DEFER (auto — deadline passed without explicit decision)

**Rationale:**

- Deadline (2026-03-04) passed without explicit COMMIT or DEFER.
- Auto-DEFER applied per ADR-001 policy.
GRAPHITI_EOF
        fi
        echo "  Auto-DEFER applied (deadline passed)"
    elif ! grep -q "Appendix A: Graphiti Decision" "$ADR" 2>/dev/null; then
        cat >> "$ADR" <<'GRAPHITI_EOF'

## Appendix A: Graphiti Decision (2026-03-04)

**Decision:** _PENDING — COMMIT or DEFER_

**Rationale:**

- Is there a concrete agent retrieval quality question we need answered? _TBD_
- Do we have bandwidth for ~1 day of prototype work Mar 5–8? _TBD_
- If no to either → DEFER

_To be completed by 2026-03-04._
GRAPHITI_EOF
        echo "  Appendix A placeholder added to: $ADR"
    else
        echo "  Appendix A already exists in: $ADR"
    fi

    echo ""
    echo "  NOTE: Update the decision (COMMIT/DEFER) by 2026-03-04"
}

# ============================================================
# Step 4: Graphiti Prototype (conditional)
# ============================================================
run_step_4() {
    step_header 4 "Graphiti Prototype"

    local ADR="$PROJECT_DIR/docs/ADR-001-graph-db-strategy.md"

    if grep -q "Decision: COMMIT" "$ADR" 2>/dev/null; then
        echo "  Graphiti approved — prototype window: 2026-03-05 to 2026-03-08"
        echo ""
        echo "  Manual steps:"
        echo "    1. docker compose up neo4j (neo4j:5-community)"
        echo "    2. pip install graphiti-core"
        echo "    3. Export 100 entities + relationships from PG"
        echo "    4. Feed through Graphiti ingestion"
        echo "    5. Run benchmark queries (2, 3, 4, 8, 9 from ADR gate list)"
        echo "    6. Write results to: scripts/graphiti/benchmark-results-${SUFFIX}.json"
    elif grep -q "Decision: DEFER" "$ADR" 2>/dev/null; then
        echo "  Graphiti DEFERRED — skipping prototype"
    else
        echo "  Graphiti decision not yet made — run step 3 first"
    fi
}

# ============================================================
# Step 5: ADR Decision Review
# ============================================================
run_step_5() {
    step_header 5 "ADR Decision Review"

    local ADR="$PROJECT_DIR/docs/ADR-001-graph-db-strategy.md"

    # Check for required artifacts
    echo "  Checking artifacts..."
    local SOAK_ARTIFACT=$(ls "$PROJECT_DIR/docs/soak-results/sync-1.5-soak-"*.md 2>/dev/null | tail -1)
    local DRILL_REPORT=$(ls "$FEDERATION_DIR/conflict-drill-report-"*.json 2>/dev/null | tail -1)

    [[ -n "$SOAK_ARTIFACT" ]] && echo "    ✓ Soak results: $SOAK_ARTIFACT" || echo "    ✗ Soak results: MISSING"
    [[ -n "$DRILL_REPORT" ]] && echo "    ✓ Drill report: $DRILL_REPORT" || echo "    ✗ Drill report: MISSING"

    if ! grep -q "Appendix B: Decision Review" "$ADR" 2>/dev/null; then
        # Read drill report overall if available
        local DRILL_OVERALL="NOT RUN"
        if [[ -n "$DRILL_REPORT" ]]; then
            DRILL_OVERALL=$(python3 -c "import json; print(json.load(open('$DRILL_REPORT'))['overall'])" 2>/dev/null || echo "ERROR")
        fi

        cat >> "$ADR" <<REVIEW_EOF

## Appendix B: Decision Review (2026-03-11)

### Soak Results
$(if [[ -n "$SOAK_ARTIFACT" ]]; then echo "_See: $(basename "$SOAK_ARTIFACT")_"; else echo "_NOT AVAILABLE_"; fi)

### Conflict Drill Results
Overall: ${DRILL_OVERALL}
$(if [[ -n "$DRILL_REPORT" ]]; then echo "_See: $(basename "$DRILL_REPORT")_"; else echo "_NOT AVAILABLE_"; fi)

### Graphiti Results
_Deferred — not evaluated_ (update if Step 4 was run)

### Decision
_PENDING: CONTINUE PG-FIRST | PROMOTE GRAPHITI SIDECAR | UNPARK TERMINUSDB_

### Deltas from Original ADR
_None yet._

### Next Review
2026-04-11 (or FINAL)
REVIEW_EOF
        echo ""
        echo "  Appendix B added to: $ADR"
    else
        echo ""
        echo "  Appendix B already exists in: $ADR"
    fi

    echo ""
    echo "  NOTE: Complete the decision section by 2026-03-11"
}

# ============================================================
# Main
# ============================================================

case "${STEP}" in
    1) run_step_1 ;;
    2) run_step_2 ;;
    3) run_step_3 ;;
    4) run_step_4 ;;
    5) run_step_5 ;;
    all)
        run_step_1
        run_step_2
        run_step_3
        ;;
    *)
        usage
        ;;
esac

echo ""
echo "============================================================"
if [[ $FAILURES -gt 0 ]]; then
    echo "  RESULT: ${FAILURES} step(s) FAILED"
    exit 1
else
    echo "  RESULT: All executed steps PASSED"
    exit 0
fi
