"""
Docstring filtering and aggregation for LLM semantic extraction.

Filters out trivial/synthetic docstrings from tree-sitter-extracted code entities
and aggregates meaningful ones into batches suitable for the OpenAI extractor.

The 3000-char batch cap matches OpenAIExtractor's max_content_length (openai_extractor.py:172).
"""

import re
from typing import List, Tuple

# Import CodeEntity type
try:
    from core.tree_sitter_extractor import CodeEntity
except ImportError:
    try:
        from src.core.tree_sitter_extractor import CodeEntity
    except ImportError:
        CodeEntity = None  # type: ignore


# Patterns that indicate synthetic/auto-generated docstrings
SYNTHETIC_PATTERNS = [
    re.compile(r"^Go package in\b", re.IGNORECASE),
    re.compile(r"^Package \w+ (?:provides|implements|contains)\b", re.IGNORECASE),
    re.compile(r"^hash:[0-9a-f]+$"),
    re.compile(r"^Auto-generated", re.IGNORECASE),
    re.compile(r"^Generated by\b", re.IGNORECASE),
    re.compile(r"^Code generated by\b", re.IGNORECASE),
    re.compile(r"^DO NOT EDIT", re.IGNORECASE),
]

# Entity types where short docstrings are usually not meaningful
VERBOSE_TYPES = {"File", "Import", "Module"}

# Minimum character thresholds
MIN_DOCSTRING_LENGTH = 60
MIN_VERBOSE_TYPE_LENGTH = 150


def is_meaningful_docstring(entity) -> bool:
    """
    Determine if a CodeEntity's docstring is worth sending to the LLM extractor.

    Filters out:
    - Empty or very short docstrings (< 60 chars after stripping)
    - Synthetic/auto-generated docstrings (e.g., "Go package in...", "hash:...")
    - File/Import/Module types with short docstrings (< 150 chars)

    Args:
        entity: A CodeEntity instance from tree_sitter_extractor

    Returns:
        True if the docstring contains meaningful content for semantic extraction
    """
    docstring = (entity.docstring or "").strip()

    if len(docstring) < MIN_DOCSTRING_LENGTH:
        return False

    # Check synthetic patterns
    for pattern in SYNTHETIC_PATTERNS:
        if pattern.search(docstring):
            return False

    # Higher threshold for verbose types that often have boilerplate
    if entity.entity_type in VERBOSE_TYPES and len(docstring) < MIN_VERBOSE_TYPE_LENGTH:
        return False

    return True


def aggregate_docstrings_for_file(
    entities: List,
    max_batch_chars: int = 3000,
) -> List[Tuple[str, List, int]]:
    """
    Group meaningful docstrings from a file into labeled batches for LLM extraction.

    Each batch is capped at max_batch_chars (matching OpenAI extractor's limit).
    Entities are formatted as labeled blocks:

        [Function: CreateBatch]
        Creates a new credit batch. Validates issuer authorization...

        [Struct: BasketKeeper]
        Manages basket operations and redemption logic...

    Args:
        entities: List of CodeEntity instances from a single file
        max_batch_chars: Maximum characters per batch (default 3000)

    Returns:
        List of (text, source_entities, batch_index) tuples where:
        - text: The aggregated docstring content for the batch
        - source_entities: The CodeEntity objects included in this batch
        - batch_index: Zero-based batch index for this file
    """
    # Filter to meaningful docstrings
    meaningful = [e for e in entities if is_meaningful_docstring(e)]

    if not meaningful:
        return []

    batches = []
    current_text = ""
    current_entities = []
    batch_index = 0

    for entity in meaningful:
        docstring = entity.docstring.strip()
        block = f"[{entity.entity_type}: {entity.name}]\n{docstring}\n\n"

        # If adding this block would exceed the cap, finalize current batch
        if current_text and len(current_text) + len(block) > max_batch_chars:
            batches.append((current_text.rstrip(), list(current_entities), batch_index))
            current_text = ""
            current_entities = []
            batch_index += 1

        current_text += block
        current_entities.append(entity)

    # Finalize last batch
    if current_text:
        batches.append((current_text.rstrip(), list(current_entities), batch_index))

    return batches
