#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_DIR="$ROOT_DIR/docs/archive/reports"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"

mkdir -p "$REPORT_DIR"

PYTHON_BIN="$ROOT_DIR/.venv/bin/python"
if [[ ! -x "$PYTHON_BIN" ]]; then
  PYTHON_BIN="python3"
fi

# Load environment if present
if [[ -f "$ROOT_DIR/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  . "$ROOT_DIR/.env"
  set +a
fi

KG_REPORT="$REPORT_DIR/kg_audit_post_extraction_${TIMESTAMP}.md"
PRED_REPORT="$REPORT_DIR/predicate_histogram_${TIMESTAMP}.json"
ALIAS_REPORT_SRC="$ROOT_DIR/data/alias_audit_report.csv"
ALIAS_REPORT_DST="$REPORT_DIR/alias_audit_report_${TIMESTAMP}.csv"
SUMMARY_REPORT="$REPORT_DIR/post_extraction_audit_${TIMESTAMP}.md"

printf "Running KG audit report...\n"
"$PYTHON_BIN" "$ROOT_DIR/scripts/kg_audit_report.py" --out "$KG_REPORT"

printf "Running predicate histogram...\n"
"$PYTHON_BIN" "$ROOT_DIR/scripts/predicate_histogram.py" --output "$PRED_REPORT"

printf "Running alias audit...\n"
"$PYTHON_BIN" "$ROOT_DIR/scripts/alias_audit.py"

if [[ -f "$ALIAS_REPORT_SRC" ]]; then
  cp "$ALIAS_REPORT_SRC" "$ALIAS_REPORT_DST"
fi

ALIAS_COUNT=0
if [[ -f "$ALIAS_REPORT_DST" ]]; then
  ALIAS_COUNT=$(tail -n +2 "$ALIAS_REPORT_DST" | wc -l | tr -d ' ')
fi

cat > "$SUMMARY_REPORT" <<MD
# Post-Extraction Audit Report (${TIMESTAMP})

Generated by: scripts/post_extraction_audit.sh

## Outputs
- KG audit: ${KG_REPORT}
- Predicate histogram: ${PRED_REPORT}
- Alias audit: ${ALIAS_REPORT_DST}

## Quick Summary
- Alias duplicates found: ${ALIAS_COUNT}

## Manual Follow-Ups
1. Review ${ALIAS_REPORT_DST} and classify merges.
2. Run type-constraint violations check (see docs/runbooks/post_extraction_audit.md).
3. (Optional) Run GraphRAG eval if relevant.
MD

printf "\nAudit complete. Summary: %s\n" "$SUMMARY_REPORT"
